### ISSUE TITLE
COMMON_SAFE_ASCII_CHARACTERS import error

### ISSUE THREAD

**Issue by stephaniewankowicz** [Herschlag-Lab/EnsemblePDB#3]
First, love this package! 

I am getting the following error running the tutorial: 

ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (/Users/stephaniewanko/opt/anaconda3/envs/PE/lib/python3.8/site-packages/charset_normalizer/constant.py)

It was solved using pip install chardet but suggest adding this to the install list.

**Comment by rkretsch** [comment]
Thanks @stephaniewankowicz It is addressed in our readme now https://github.com/Herschlag-Lab/EnsemblePDB/blob/main/README.md#install

```
conda create --name PE python=3.8
conda activate PE
python setup.py install
conda install pandas=1.4.4
pip install pypdb==2.3
pip install biopandas==0.4.1
pip install tqdm==4.66.1
pip install biopython==1.82
pip install scikit-learn==1.3.2
conda install -c schrodinger pymol=2.4
pip install chardet==5.2.0
```
